package com.android.face_discern.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.android.face_discern.model.Contrast;
import com.android.face_discern.model.User;

import com.android.face_discern.db.ContrastDao;
import com.android.face_discern.db.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contrastDaoConfig;
    private final DaoConfig userDaoConfig;

    private final ContrastDao contrastDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contrastDaoConfig = daoConfigMap.get(ContrastDao.class).clone();
        contrastDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        contrastDao = new ContrastDao(contrastDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Contrast.class, contrastDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        contrastDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public ContrastDao getContrastDao() {
        return contrastDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
